# .github/workflows/linux.yml
name: linux

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"
  pull_request:

jobs:
  perl_tester:
    runs-on: ubuntu-latest
    name: "perl v${{ matrix.perl-version }}"

    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - "5.32"
          - "5.30"
          - "5.28"
          - "5.26"
          - "5.14"

    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}

    steps:
      - run: apt-get update
      - run: apt-get install -y libldns-dev
      - uses: actions/checkout@v2
      - name: install deps using cpm
        uses: perl-actions/install-with-cpm@v1.3
        with:
          install: |
            Test::Exception
          sudo: false
      - run: perl Makefile.PL
      - run: make
      - run: make test